version: '3.8'

services:
  # 1. Database (Standard Postgres)
  postgres:
    image: postgres:15-alpine
    container_name: crm_postgres
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
      POSTGRES_DB: crm_db
    ports:
      - "5433:5432"  # <-- Mapped to 5433 to avoid conflict with your Windows Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Cache (Redis)
  redis:
    image: redis:alpine
    container_name: crm_redis
    ports:
      - "6379:6379"

  # 3. The Event Broker (Redpanda)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: crm_redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
    ports:
      - "19092:19092"
      - "18081:18081"
      - "18082:18082"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  postgres_data:
  redpanda_data: